# Generated by Django 4.2.4 on 2023-08-31 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("small_title", models.CharField(max_length=100)),
                ("content", models.TextField(blank=True)),
                ("author_name", models.CharField(max_length=10)),
                ("modify_date", models.DateTimeField(auto_now=True)),
                ("create_date", models.DateField(auto_now_add=True)),
                (
                    "article_photo",
                    models.ImageField(max_length=255, upload_to="article_photo"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="article_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_category", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=10)),
                ("position", models.CharField(max_length=10)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mysite.article"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="article_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.article_category",
            ),
        ),
    ]
