# Generated by Django 4.2.4 on 2023-09-05 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0002_manager_category_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="banner_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banner_category", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_photo",
                    models.ImageField(max_length=255, upload_to="project_photo"),
                ),
                ("big_title", models.CharField(max_length=50)),
                ("little_title", models.CharField(max_length=50)),
                ("modify_date", models.DateTimeField(auto_now=True)),
                ("create_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banner_photo",
                    models.ImageField(max_length=255, upload_to="banner_photo"),
                ),
                ("modify_date", models.DateTimeField(auto_now=True)),
                ("create_date", models.DateField(auto_now_add=True)),
                (
                    "banner_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.banner_category",
                    ),
                ),
            ],
        ),
    ]
