# Generated by Django 4.2.4 on 2023-09-06 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0003_banner_category_project_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="department_form_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_form_category", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="department_form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_name", models.CharField(max_length=50)),
                ("form_link", models.CharField(max_length=100)),
                (
                    "department_form_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.department_form_category",
                    ),
                ),
            ],
        ),
    ]
