# Generated by Django 4.2.4 on 2023-09-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0004_department_form_category_department_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="department_form",
            name="modify_date",
            field=models.DateTimeField(auto_now=True, verbose_name="修改時間"),
        ),
        migrations.AddField(
            model_name="department_form",
            name="modify_user",
            field=models.CharField(default=2023, max_length=50, verbose_name="修改者"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="article_photo",
            field=models.ImageField(
                max_length=255, upload_to="article_photo", verbose_name="文章圖片"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="author_name",
            field=models.CharField(max_length=10, verbose_name="作者"),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, verbose_name="文案"),
        ),
        migrations.AlterField(
            model_name="article",
            name="small_title",
            field=models.CharField(max_length=100, verbose_name="小標題"),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=50, verbose_name="標題"),
        ),
        migrations.AlterField(
            model_name="article_category",
            name="article_category",
            field=models.CharField(max_length=10, verbose_name="文章類別"),
        ),
        migrations.AlterField(
            model_name="department_form",
            name="form_link",
            field=models.CharField(max_length=100, verbose_name="表單連結"),
        ),
        migrations.AlterField(
            model_name="department_form",
            name="form_name",
            field=models.CharField(max_length=50, verbose_name="表單名稱"),
        ),
        migrations.AlterField(
            model_name="department_form_category",
            name="department_form_category",
            field=models.CharField(max_length=50, verbose_name="表單存放部門"),
        ),
    ]
