# Generated by Django 4.2.4 on 2023-09-08 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0005_department_form_modify_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="common_link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_title", models.CharField(max_length=50, verbose_name="常用連結名稱")),
                ("link_href", models.CharField(max_length=100, verbose_name="使用連結或說明")),
            ],
        ),
        migrations.AlterField(
            model_name="department_form",
            name="department_form_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mysite.department_form_category",
                verbose_name="表單存放部門",
            ),
        ),
    ]
